require("gruvbox").setup {
  terminal_colors = true, -- add gruvbox terminal colors- disable if you want true terminal colors
  undercurl = true,
  underline = true,
  bold = true,
  italic = {
    strings = true,
    emphasis = true,
    comments = true,
    operators = false,
    folds = true,
  },
  strikethrough = true,
  invert_selection = false,
  invert_signs = false,
  invert_tabline = false,
  invert_intend_guides = false,
  inverse = true, -- invert background for search, diffs, statuslines and errors
  contrast = "hard", -- can be "hard", "soft" or empty string
  palette_overrides = {},
  overrides = {
    Normal = { bg = "#0E1018" },
    VertSplit = { bg = "#0E1018", fg = "NONE" },
    SignColumn = { bg = "NONE" },
    Define = { link = "GruvboxPurple" },
    Macro = { link = "GruvboxPurple" },
    ["@constant.builtin"] = { link = "GruvboxPurple" },
    ["@storageclass.lifetime"] = { link = "GruvboxAqua" },
    ["@text.note"] = { link = "TODO" },
    ContextVt = { fg = "#878787" },
    Comment = { fg = "#fe8019", italic = true },
    Folded = { italic = true, fg = "#fe8019", bg = "#3c3836" },
    FoldColumn = { fg = "#fe8019", bg = "#0E1018" },
    DiffAdd = { bold = true, reverse = false, fg = "", bg = "#2a4333" },
    DiffChange = { bold = true, reverse = false, fg = "", bg = "#333841" },
    DiffDelete = { bold = true, reverse = false, fg = "#442d30", bg = "#442d30" },
    DiffText = { bold = true, reverse = false, fg = "", bg = "#213352" },
    StatusLine = { bg = "#ffffff", fg = "#0E1018" },
    StatusLineNC = { bg = "NONE", fg = "#0E1018" },
    CursorLineNr = { fg = "#fabd2f", bg = "#0E1018" },
    CursorLine = { bg = "NONE" },
    Pmenu = { bg = "NONE" },
    PmenuSel = { bg = "#83a598" },
    DiagnosticVirtualTextWarn = { fg = "#dfaf87" },
    DiagnosticUnderlineError = { fg = "NONE" },
    DiagnosticUnderlineInfo = { fg = "NONE" },
    DiagnosticUnderlineWarn = { fg = "NONE" },
    DiagnosticUnderlineHint = { fg = "NONE" },
    GruvboxOrangeSign = { fg = "#dfaf87", bg = "NONE" },
    GruvboxAquaSign = { fg = "#8EC07C", bg = "NONE" },
    GruvboxGreenSign = { fg = "#b8bb26", bg = "NONE" },
    GruvboxRedSign = { fg = "#fb4934", bg = "NONE" },
    GruvboxBlueSign = { fg = "#83a598", bg = "NONE" },
    WilderMenu = { fg = "#ebdbb2", bg = "#0E1018" },
    WilderAccent = { fg = "#f4468f", bg = "#0E1018" },
  },
  dim_inactive = false,
  transparent_mode = true,
}

vim.cmd.colorscheme "gruvbox"
