-- Plugin configurations
require('plugins.dap')
require('plugins.lsp')
require('plugins.key')
require('plugins.tree')
require('plugins.mason')
require('plugins.alpha')
require('plugins.notify')
require('plugins.indent')
require('plugins.lualine')
require('plugins.autopair')
require('plugins.catppuccin')
require('plugins.bufferline')
require('plugins.completion')
