#!/usr/bin/env sh

# osascript -e 'tell application id "tracesOf.Uebersicht" to refresh'

#sudo yabai --load-sa
#yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"

## global settings
#yabai -m config mouse_follows_focus          off
#yabai -m config focus_follows_mouse          off
#yabai -m config window_placement             second_child
#yabai -m config window_topmost               off
#yabai -m config window_shadow                off
#yabai -m config window_border                on
#yabai -m config window_border_width          2
#yabai -m config window_border_radius         0
#yabai -m config window_border_blur           off
#yabai -m config active_window_border_color   0xFF5CCC96
#yabai -m config normal_window_border_color   0xFFECF0C1
#yabai -m config insert_feedback_color        0xFFFF4250
#yabai -m config split_ratio                  0.50
#yabai -m config auto_balance                 off
#yabai -m config mouse_modifier               fn
#yabai -m config mouse_action1                move
#yabai -m config mouse_action2                resize
#yabai -m config mouse_drop_action            swap

## general space settings
#yabai -m config layout                       float
#yabai -m config top_padding                  08
#yabai -m config bottom_padding               08
#yabai -m config left_padding                 08
#yabai -m config right_padding                08
#yabai -m config window_gap                   08


# default layout (can be bsp, stack or float)
yabai -m config layout bsp

# new window spawns to the right if vertical split, or bottom if horizontal split
yabai -m config window_placement second_child

# padding set to 12px
yabai -m config top_padding 12
yabai -m config bottom_padding 12
yabai -m config left_padding 12
yabai -m config right_padding 12
yabai -m config window_gap 12

# -- mouse settings --

# center mouse on window with focus
yabai -m config mouse_follows_focus on

# modifier for clicking and dragging with mouse
yabai -m config mouse_modifier alt
# set modifier + left-click drag to move window
yabai -m config mouse_action1 move
# set modifier + right-click drag to resize window
yabai -m config mouse_action2 resize

# when window is dropped in center of another window, swap them (on edges it will split it)
yabai -m mouse_drop_action swap


# disable specific apps
yabai -m rule --add app="^System Settings$" manage=off
yabai -m rule --add app="^Calculator$" manage=off
yabai -m rule --add app="^Karabiner-Elements$" manage=off
yabai -m rule --add app="^QuickTime Player$" manage=off

yabai -m config external_bar all:32:0
